const majorsArr = [
  "Agribusiness",
  "Agricultural Education and Communication",
  "Animal Science",
  "BioResource and Agricultural Engineering",
  "Experience Industry Management",
  "Food Science and Nutrition",
  "Horticulture and Crop Science",
  "Military Science",
  "Natural Resources Management and Environmental Sciences",
  "Wine and Viticulture",
  "Architectural Engineering",
  "Architecture",
  "City and Regional Planning",
  "Construction Management",
  "Landscape Architecture",
  "Aerospace Engineering",
  "Biomedical Engineering",
  "Civil and Environmental Engineering",
  "Computer Engineering",
  "Computer Science and Software Engineering",
  "Electrical Engineering",
  "General Engineering",
  "Industrial and Manufacturing Engineering",
  "Materials Engineering",
  "Mechanical Engineering",
  "Art and Design",
  "Communication Studies",
  "English",
  "Ethnic Studies",
  "Graphic Communication",
  "History",
  "Interdisciplinary Studies in the Liberal Arts",
  "Journalism",
  "Music",
  "Philosophy",
  "Political Science",
  "Psychology and Child Development",
  "Social Sciences",
  "Theatre and Dance",
  "Women's and Gender Studies",
  "World Languages and Cultures",
  "Biological Sciences",
  "Chemistry and Biochemistry",
  "Kinesiology and Public Health",
  "Liberal Studies",
  "Mathematics",
  "Physics",
  "Statistics",
  "School of Education",
  "Accounting",
  "Business Administration",
  "Economics",
  "Entrepreneurship",
  "Industrial Technology",
  "Integrated Marketing Communications",
  "Sales"];
  
export default majorsArr;